### ISSUE TITLE
Standard deviation of results.

### ISSUE THREAD

**Issue by kadarsh22** [facebookresearch/Whac-A-Mole#5]
Hi, Thank you for this wonderful piece of work and code. It would be great if you could provide the std deviation of results given in the paper at least for (Tables 3, 4, and 5).

**Comment by zhihengli-UR** [comment]
Hi,

Thank you for your interests in our work!

On UrbanCars (Tables 3,5), we run experiments 6 times using different random seeds (see Appendix B.3). Unfortunately I don't have access to the standard deviations of the results anymore.

On ImageNet (Table 4), we "tune the learning rate over {10^{-2}, 10^{-3}, 10^{-4}} and choose the one with the best top-1 accuracy on IN-1k." (see Appendix B.3). Thus, we don't have standard deviation results. We did not run experiments on ImageNet multiple times because it is more costly due to much larger data size compared to UrbanCars.

Let me know if you have any other questions.
